name: Deploy docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build docs for CDN
        run: npm install && npm run build:cdn
      - name: Install UploadCDN Client
        run: wget https://github.com/gotomicro/uploadcdn/releases/download/v0.1.0/uploadcdn-client.tar.gz && tar xvf uploadcdn-client.tar.gz && chmod 755 uploadcdn-client
      - name: Upload docs to CDN
        run: export EGO_DEBUG=true && ./uploadcdn-client -id=${{ secrets.UPLOAD_CDN_CLIENT_ID }} -addr=http://upload.gocn.vip -secret=${{ secrets.UPLOAD_CDN_CLIENT_SECRET }} -dir=./docs/.vuepress/dist
      - name: Build docs for GitHub Pages
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
